apiVersion: v1
kind: ConfigMap
metadata:
  name: easyshop-config
  namespace: easyshop-ns
data:
  MONGODB_URI: "mongodb://mongodb-service:27017/easyshop"
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "https://easyshop.freshfinds.site/api"  # <==========  freshfinds.site 
  NEXTAUTH_URL: "https://easyshop.freshfinds.site/"            # <==========   freshfinds.site 
  JWT_SECRET: "VtRPtM4egYdYNoxdcDHka9Fn3Tp2tbOc76DJRxFhacw="
  NEXTAUTH_SECRET: "ICvHMffoZGy03nWbW/9PPnRobzlAJo2d9MiLOVwOcDE="
