apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: easyshop-ing
  namespace: easyshop-ns
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - easyshop.freshfinds.site
    secretName: easyshop-tls-secret
  rules:
  - host: easyshop.freshfinds.site
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: easyshop-svc
            port: 
              number: 80
