apiVersion: v1
kind: Secret
metadata:
  name: easyshop-secrets
  namespace: easyshop-ns
type: opaque  
stringData:
  JWT_SECRET: "VtRPtM4egYdYNoxdcDHka9Fn3Tp2tbOc76DJRxFhacw="
  NEXTAUTH_SECRET: "ICvHMffoZGy03nWbW/9PPnRobzlAJo2d9MiLOVwOcDE="

