apiVersion: v1
kind: Service
metadata:
  name: easyshop-svc
  namespace: easyshop-ns
spec:
  type: NodePort
  selector:
    app: easyshop
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30000 
